//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.312
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchFile.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SearchFile.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   すべてのファイル (*.*)|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AllFileDialogFilter {
            get {
                return ResourceManager.GetString("AllFileDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検索結果をクリアしました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ClearFilesMessage {
            get {
                return ResourceManager.GetString("ClearFilesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} 個のファイル名をコピーしました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CopyFileNameMessage {
            get {
                return ResourceManager.GetString("CopyFileNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検索結果が空です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CopyTargetFilesEmptyMessage {
            get {
                return ResourceManager.GetString("CopyTargetFilesEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ディレクトリが存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DirectoryNotFoundMessage {
            get {
                return ResourceManager.GetString("DirectoryNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorDialogCaption {
            get {
                return ResourceManager.GetString("ErrorDialogCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除処理をキャンセルしました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileDeleteCancelMessage {
            get {
                return ResourceManager.GetString("FileDeleteCancelMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除処理中にエラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileDeleteErrorMessage {
            get {
                return ResourceManager.GetString("FileDeleteErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} 個のファイルを削除しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileDeleteMessage {
            get {
                return ResourceManager.GetString("FileDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検索するフォルダを選択してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FolderBrowserDialogDescription {
            get {
                return ResourceManager.GetString("FolderBrowserDialogDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検索するファイル名を入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotInputFileNameMessage {
            get {
                return ResourceManager.GetString("NotInputFileNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検索パターンが指定されていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotSelectSearchPatternMessage {
            get {
                return ResourceManager.GetString("NotSelectSearchPatternMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string QuestionDialogCaption {
            get {
                return ResourceManager.GetString("QuestionDialogCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検索結果をクリアしてもよろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string QuestionFilesClearMessage {
            get {
                return ResourceManager.GetString("QuestionFilesClearMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} を検索中... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SearchingDirectoryMessage {
            get {
                return ResourceManager.GetString("SearchingDirectoryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検索中にエラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SearchingErrorMessage {
            get {
                return ResourceManager.GetString("SearchingErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} 個のファイルが見つかりました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SearchingResultMessage {
            get {
                return ResourceManager.GetString("SearchingResultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検索を中止しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SearchingStopMessage {
            get {
                return ResourceManager.GetString("SearchingStopMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検索開始(&amp;S) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SearchStartButtonText {
            get {
                return ResourceManager.GetString("SearchStartButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検索中止(&amp;S) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SearchStopButtonText {
            get {
                return ResourceManager.GetString("SearchStopButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラーメッセージ: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShowErrorDetailsTitle {
            get {
                return ResourceManager.GetString("ShowErrorDetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テキストファイル (*.txt)|*.txt に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TextFileDialogFilter {
            get {
                return ResourceManager.GetString("TextFileDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検索結果の表示処理中に例外が発生しました。検索処理を中止しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UIErrorQuestion {
            get {
                return ResourceManager.GetString("UIErrorQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル名に使用できない文字が含まれています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UsingInvalidFileNameMessage {
            get {
                return ResourceManager.GetString("UsingInvalidFileNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   警告 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WarningDialogCaption {
            get {
                return ResourceManager.GetString("WarningDialogCaption", resourceCulture);
            }
        }
    }
}
