//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.42
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchFile.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "8.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ディレクトリ名(&D):")]
        public string labelDirectory_Text {
            get {
                return ((string)(this["labelDirectory_Text"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ディレクトリの選択")]
        public string buttonDirectory_Text {
            get {
                return ((string)(this["buttonDirectory_Text"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ファイル名(&F):")]
        public string labelFile_Text {
            get {
                return ((string)(this["labelFile_Text"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ワイルドカード")]
        public string radioWildcard_Text {
            get {
                return ((string)(this["radioWildcard_Text"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("正規表現")]
        public string radioRegex_Text {
            get {
                return ((string)(this["radioRegex_Text"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("検索開始(&S)")]
        public string buttonSearch_Text {
            get {
                return ((string)(this["buttonSearch_Text"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("検索中止(&S)")]
        public string buttonSearch_StopText {
            get {
                return ((string)(this["buttonSearch_StopText"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("リストのクリア")]
        public string buttonClear_Text {
            get {
                return ((string)(this["buttonClear_Text"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("すべて選択")]
        public string buttonSelectAll_Text {
            get {
                return ((string)(this["buttonSelectAll_Text"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("選択の切り替え")]
        public string buttonReverseSelection_Text {
            get {
                return ((string)(this["buttonReverseSelection_Text"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("選択ファイルを削除する")]
        public string buttonDeleteFile_Text {
            get {
                return ((string)(this["buttonDeleteFile_Text"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("削除時にファイルをごみ箱に移す")]
        public string checkMoveRecycler_Text {
            get {
                return ((string)(this["checkMoveRecycler_Text"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ファイル名")]
        public string columnFileName_Text {
            get {
                return ((string)(this["columnFileName_Text"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("拡張子")]
        public string columnExtension_Text {
            get {
                return ((string)(this["columnExtension_Text"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ディレクトリ")]
        public string columnDirectoryName_Text {
            get {
                return ((string)(this["columnDirectoryName_Text"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ファイル(&F)")]
        public string menuFile_Text {
            get {
                return ((string)(this["menuFile_Text"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("編集(&E)")]
        public string menuEdit_Text {
            get {
                return ((string)(this["menuEdit_Text"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("検索結果をコピー(&C)")]
        public string menuEditCopy_Text {
            get {
                return ((string)(this["menuEditCopy_Text"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("すべて選択(&A)")]
        public string menuEditSelectAll_Text {
            get {
                return ((string)(this["menuEditSelectAll_Text"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("選択の切り替え(&R)")]
        public string menuEditReverseSelection_Text {
            get {
                return ((string)(this["menuEditReverseSelection_Text"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("リストのクリア(&C)")]
        public string menuFileClear_Text {
            get {
                return ((string)(this["menuFileClear_Text"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ディレクトリの選択(&S)...")]
        public string menuFileSelectDirectory_Text {
            get {
                return ((string)(this["menuFileSelectDirectory_Text"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("名前を付けて保存(&A)...")]
        public string menuFileSaveAs_Text {
            get {
                return ((string)(this["menuFileSaveAs_Text"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("終了(&X)")]
        public string menuFileExit_Text {
            get {
                return ((string)(this["menuFileExit_Text"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ファイルの検索")]
        public string SearchFileForm_Text {
            get {
                return ((string)(this["SearchFileForm_Text"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("リストのクリア")]
        public string toolFileClear_Text {
            get {
                return ((string)(this["toolFileClear_Text"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ディレクトリの選択")]
        public string toolFileSelectDirectory_Text {
            get {
                return ((string)(this["toolFileSelectDirectory_Text"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("名前を付けて保存")]
        public string toolFileSaveAs_Text {
            get {
                return ((string)(this["toolFileSaveAs_Text"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("検索結果をコピー")]
        public string toolEditResultCopy_Text {
            get {
                return ((string)(this["toolEditResultCopy_Text"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("切り取り")]
        public string toolEditCut_Text {
            get {
                return ((string)(this["toolEditCut_Text"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("コピー")]
        public string toolEditCopy_Text {
            get {
                return ((string)(this["toolEditCopy_Text"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("貼り付け")]
        public string toolEditPaste_Text {
            get {
                return ((string)(this["toolEditPaste_Text"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("リストのクリア(&C)")]
        public string contextFileListClear_Text {
            get {
                return ((string)(this["contextFileListClear_Text"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("検索結果をコピー(&O)")]
        public string contextFileListResultCopy_Text {
            get {
                return ((string)(this["contextFileListResultCopy_Text"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("すべて選択(&A)")]
        public string contextFileListSelectAll_Text {
            get {
                return ((string)(this["contextFileListSelectAll_Text"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("選択の切り替え(&R)")]
        public string contextFileListReverseSelection_Text {
            get {
                return ((string)(this["contextFileListReverseSelection_Text"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("検索時に列幅を自動調整(&W)")]
        public string contextFileListAutoColumnWidth_Text {
            get {
                return ((string)(this["contextFileListAutoColumnWidth_Text"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("プロパティの表示(&P)")]
        public string contextFileListShowProperty_Text {
            get {
                return ((string)(this["contextFileListShowProperty_Text"]));
            }
        }
    }
}
